name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.16.3
  MARIADB114: '11.4.4'
  MARIADB1011: '10.11.10'
  MARIADB106: '10.6.20'
  MARIADB105: '10.5.27'
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  mariadb114-build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            arch: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB114 }}
          ARCH: ${{ matrix.arch }}
          PLATFORM: ${{ matrix.platform }}
        working-directory: 11
        run: |
          make buildx-build
          make test
          make buildx-push
  mariadb114-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb114-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB114 }}
          workdir: 11
          latest: true
          latest_major: true

  mariadb1011-build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            arch: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB1011 }}
          ARCH: ${{ matrix.arch }}
          PLATFORM: ${{ matrix.platform }}
        working-directory: 10
        run: |
          make buildx-build
          make test
          make buildx-push
  mariadb1011-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb1011-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB1011 }}
          workdir: 10
          latest_major: true

  mariadb106-build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            arch: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB106 }}
          ARCH: ${{ matrix.arch }}
          PLATFORM: ${{ matrix.platform }}
        working-directory: 10
        run: |
          make buildx-build
          make test
          make buildx-push
  mariadb106-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb106-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB106 }}
          workdir: 10

  mariadb105-build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            arch: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB105 }}
          ARCH: ${{ matrix.arch }}
          PLATFORM: ${{ matrix.platform }}
        working-directory: 10
        run: |
          make buildx-build
          make test
          make buildx-push
  mariadb105-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb105-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB105 }}
          workdir: 10
