name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

env:
  BASE_IMAGE_STABILITY_TAG: 2.18.2
  MARIADB114: '11.4.8'
  MARIADB1011: '10.11.13'
  MARIADB106: '10.6.22'
  MARIADB105: '10.5.29'

jobs:
  mariadb114-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB114 }}
          ARCH: ${{ matrix.arch }}
        working-directory: 11
        run: |
          make
          make test
          make push
  mariadb114-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb114-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB114 }}
          workdir: 11
          latest: true
          latest_major: true

  mariadb1011-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB1011 }}
          ARCH: ${{ matrix.arch }}
        working-directory: 10
        run: |
          make
          make test
          make push
  mariadb1011-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb1011-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB1011 }}
          workdir: 10
          latest_major: true

  mariadb106-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB106 }}
          ARCH: ${{ matrix.arch }}
        working-directory: 10
        run: |
          make
          make test
          make push
  mariadb106-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb106-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB106 }}
          workdir: 10

  mariadb105-build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          MARIADB_VER: ${{ env.MARIADB105 }}
          ARCH: ${{ matrix.arch }}
        working-directory: 10
        run: |
          make
          make test
          make push
  mariadb105-push:
    runs-on: ubuntu-latest
    needs:
      - mariadb105-build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ env.MARIADB105 }}
          workdir: 10
